### ISSUE TITLE
Zamunda приставка не зарежда

### ISSUE THREAD

**Issue by yasenmf1** [svetlozardraganov/stremio-addon-zamunda#1]
Привет с версия 4.4.168 на Stremio Замунда пристваката не зарежда 
![zamunda](https://github.com/svetlozardraganov/stremio-addon-zamunda/assets/167629217/6d250085-eea0-4117-9eb6-aef252a246e9)

**Comment by svetlozardraganov** [comment]
Благодаря, ще проверя какво се случва.

Възможно е да е от сървъра на Stremio, последните 1-2 седмици сървъра доста често се претоварваше и доста често Zamunda, както и други приставки не работеха нормално. От Stremio ме уведомиха че работят по отстраняването на проблема.

Би било полезно ако споделите повече обратна връзка за приставката. Например, на какво устройство я използвате, колко често я използвате, работи ли както очаквате или постоянно срещате проблеми и т.н. Тази информация ще ми помогне да подобря приставката.

Благодаря ви предварително!

**Comment by yasenmf1** [comment]
![субс)shogun](https://github.com/svetlozardraganov/stremio-addon-zamunda/assets/167629217/7cc4bb87-7296-4947-ad7f-d0129522a2e1)
Привет, позлвам я поне 3 пъти седмично.
На Dsktop машина.
Давам пример със сериала Луцифер - замунда приствката липсва, кат source.
готов съм да правим тестове, за да покараем тази ваша безценна пиставка
![lucifer_zamunda](https://github.com/svetlozardraganov/stremio-addon-zamunda/assets/167629217/33293756-b67c-4683-afeb-9c197ee9205e)
![zamunda_adoon](https://github.com/svetlozardraganov/stremio-addon-zamunda/assets/167629217/5c7401e0-84a8-4728-a89d-bf62069d65b7)
Сега давам пример със серила Шогун - има source, но няма субс.
![shogun stremio](https://github.com/svetlozardraganov/stremio-addon-zamunda/assets/167629217/d306aafa-402b-4a94-a12b-6b5f4d1dc567)

**Comment by yasenmf1** [comment]
Втоарата проба е със серила Шогун, има source няма субс

**Comment by svetlozardraganov** [comment]
Благодаря за подробната информация,

Проблема с липсващият source, изглежда да е проблем със сървърите на Stremio. Това е една от причините поради която съм се свързал с тях. Има някакво претоварване на сървърите, днес дори не ми позволява да кача ъпдейт на приставката, самият сървър приема заявката но не я финишира успешно.

Иначе с локална инсталация при мен, приставката успява успешно да генерира source за сериала Lucifer:
![image](https://github.com/svetlozardraganov/stremio-addon-zamunda/assets/74985932/e3f7a5ad-f112-4a0d-a171-2f8044ffb8ec)

Относно липсващите субтитри - б момента субтитрите са направени да работят само за филми. Ще добавя възможност субтитрите да се зареждат и за сериалите, но преди това ми се иска да се отстрани проблема със откриването на source-ове, тъй като той е доста по генерален.

**Comment by yasenmf1** [comment]
Възможно ли да е се "бие" с някоя друга приставка? Ползвам Real debrid and Orion API

**Comment by svetlozardraganov** [comment]
Не би следвало, приставките на Stremio работят независимо една от друга, те буквално са отделни програми.

**Comment by yasenmf1** [comment]
Сега пуснах legend of the seeker 
![leeg](https://github.com/svetlozardraganov/stremio-addon-zamunda/assets/167629217/f558e8ce-b164-4f89-86c5-5280313fef12)
![leeg+zam](https://github.com/svetlozardraganov/stremio-addon-zamunda/assets/167629217/02413ecd-c807-4f04-ba5c-fbd10ca5a1b5)

**Comment by yasenmf1** [comment]
НА Dune part two работи перфектно

**Comment by yasenmf1** [comment]
Между другото стремио са бг, не знам дали знаете :)

**Comment by svetlozardraganov** [comment]
> Сега пуснах legend of the seeker

Legend Of The Seeker - е доста стар и не е много популярен сериал. Почти никога няма достатъчен брой сиидъри, следователно е почти невъзможно да се streem-ва.

> НА Dune part two работи перфектно
Dune Part Two - точно обратното на Legend Of The Seeker, популярен и доста seed-ъри и се очаква да работи доста добре.

> Между другото стремио са бг, не знам дали знаете :)
Знам да.

**Comment by svetlozardraganov** [comment]
> The subtitles http request that is sent from Stremio for Legend Of The Seeker s01e01 is like: https://c0a3c220c521-stremio-zamunda.baby-beamup.club/subtitles/series/tt0844653%3A1%3A1/filename=Legend.of.the.Seeker.S01E01.WEBRip.x264-ION10.mp4&videoSize=898974259&videoHash=3bf76735bd182903.json but the response body is empty


Thanks for reporting this!
Subtitles are not yet supported for Series, only for Movies.
I will add support for Series as soon as I managed to fix a more important issue related to the addon-stability.

**Comment by bankov4eto** [comment]
Благодаря за страхотната добавка. Аз установих проблем примерно с филма Аватар който дава резултат само на 1ва част със смесени резултати от Аватар 1 и Аватар 2. А когато опитам да достъпя линове от Аватар 2 няма резултати.
Другият филм се казва IF все още няма линкове за него но приставката дава резултати от сериала What if.

**Comment by svetlozardraganov** [comment]
> Thats the subs request for dune part two: https://c0a3c220c521-stremio-zamunda.baby-beamup.club/subtitles/movie/tt15239678/filename=Dune.Part.Two.2024.1080p.WEBRip.x265.DDP5.1.Atmos-WAR.mkv&videoSize=5929613631&videoHash=e80e912b1d94a3f3.json

Managed to replicate it - will be fixed.

**Comment by svetlozardraganov** [comment]
> Благодаря за страхотната добавка. Аз установих проблем примерно с филма Аватар който дава резултат само на 1ва част със смесени резултати от Аватар 1 и Аватар 2. А когато опитам да достъпя линове от Аватар 2 няма резултати. Фима Dune показва линкове само ако се достъпи от Филма от 1984 година - съответно пак със смесени линкове.

Благодаря за обратната връзка.
Това е очаквано и е поведението на zamunda-търсачката. Ако използвате ключова дума **Avatar** zamunda ще ви върне резултати и за Avatar 1  и за Avatar 2. 

За съжаление информацията в Title-a на торентите в zamunda e изключително неконсистентно, и няма лесен начин да се провери дали намереният торент в zamunda отговаря на избраният филм в Stremio. Има вариант това да бъде подобрено, чрез използването на IMBB линка към торента. За съжаление обаче не всички торенти имат добавен IMDB линк, т.е. дори и това подобрение няма да отстрани проблема на 100%, но ще го намали.

Останалите торент добавки в Stremio работят с тракери които имат стандартизация на информацията, което гарантира че намерените резултати ще съответстват на 100% спрямо подадената заявка за търсене от Stremio.

**Comment by svetlozardraganov** [comment]
Здравейте,

Направил съм доста подобрения по приставката. 

- Стиймовете би трябвало да се зареждат веднага, без да има нужда от изчакване, както беше преди.
- Коригирани са проблемите с незареждането или ненамирането на дадени стриймове.
- Вече би следвало да се показват само правилните стриймове, т.е. ако се м подаде заявка за Avatar, не би следвало да се показват стриймове за Avatar 2.

За в момента съм премахнал възможността да се зареждат субтитри тъй като поради някаква причина Стремио доста често не може да ги зареди в правилният encoding. Не знам каква е причината за това, и разработчиците на Стремио също не знаят каква е причината за това. 

Ако забележите някакви други проблеми не се притеснявайте да ги споделите за да мога да ги коригирам :)
